{
  "components": {
    "securitySchemes": {
      "accessTokenBearer": {
        "description": "The `access_token` obtained during [account registration](https://spec.matrix.org/v1.17/client-server-api/#account-registration)\nor [login](https://spec.matrix.org/v1.17/client-server-api/#login), using the `Authorization: Bearer` header.\n\nIt can also be the `as_token` of an application service.\n\nThis is the preferred method.",
        "scheme": "bearer",
        "type": "http"
      }
    }
  },
  "security": [
    {
      "accessTokenBearer": []
    }
  ],
  "info": {
    "title": "Matrix Client-Server API",
    "version": "v1.17"
  },
  "openapi": "3.1.0",
  "paths": {
    "/_matrix/client/v3/account/whoami": {
      "get": {
        "description": "Gets information about the owner of a given access token.\n\nNote that, as with the rest of the Client-Server API,\nApplication Services may masquerade as users within their\nnamespace by giving a `user_id` query parameter. In this\nsituation, the server should verify that the given `user_id`\nis registered by the appservice, and return it in the response\nbody.",
        "operationId": "getTokenOwner",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "device_id": "ABC1234",
                      "user_id": "@joe:example.org"
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "device_id": {
                      "description": "Device ID associated with the access token. If no device\nis associated with the access token (such as in the case\nof application services) then this field can be omitted.\nOtherwise this is required.",
                      "type": "string",
                      "x-addedInMatrixVersion": "1.1"
                    },
                    "is_guest": {
                      "description": "When `true`, the user is a [Guest User](https://spec.matrix.org/v1.17/client-server-api/#guest-access).\nWhen not present or `false`, the user is presumed to be a \nnon-guest user.",
                      "type": "boolean",
                      "x-addedInMatrixVersion": "1.2"
                    },
                    "user_id": {
                      "description": "The user ID that owns the access token.",
                      "format": "mx-user-id",
                      "pattern": "^@",
                      "type": "string"
                    }
                  },
                  "required": [
                    "user_id"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "The token belongs to a known user."
          },
          "401": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "errcode": "M_UNKNOWN_TOKEN",
                      "error": "Unrecognised access token."
                    }
                  }
                },
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "The token is not recognised"
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "errcode": "M_FORBIDDEN",
                      "error": "Application service has not registered this user."
                    }
                  }
                },
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "The appservice cannot masquerade as the user or has not registered them."
          },
          "429": {
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "description": "A Matrix-level Error",
                      "properties": {
                        "errcode": {
                          "description": "An error code.",
                          "example": "M_UNKNOWN",
                          "type": "string"
                        },
                        "error": {
                          "description": "A human-readable error message.",
                          "example": "An unknown error occurred",
                          "type": "string"
                        }
                      },
                      "required": [
                        "errcode"
                      ],
                      "title": "Error",
                      "type": "object"
                    },
                    {
                      "description": "The rate limit was reached for this request",
                      "properties": {
                        "errcode": {
                          "description": "The M_LIMIT_EXCEEDED error code",
                          "example": "M_LIMIT_EXCEEDED",
                          "type": "string"
                        },
                        "error": {
                          "description": "A human-readable error message.",
                          "example": "Too many requests",
                          "type": "string"
                        },
                        "retry_after_ms": {
                          "description": "The amount of time in milliseconds the client should wait\nbefore trying the request again.",
                          "example": 2000,
                          "type": "integer"
                        }
                      },
                      "required": [
                        "errcode"
                      ],
                      "title": "RateLimitError",
                      "type": "object"
                    }
                  ]
                }
              }
            },
            "description": "This request was rate-limited."
          }
        },
        "summary": "Gets information about the owner of an access token.",
        "tags": [
          "Session management"
        ]
      }
    },
    "/_matrix/client/v3/createRoom": {
      "post": {
        "description": "Create a new room with various configuration options.\n\nThe server MUST apply the normal state resolution rules when creating\nthe new room, including checking power levels for each event. It MUST\napply the events implied by the request in the following order:\n\n1. The `m.room.create` event itself. Must be the first event in the\n   room.\n\n2. An `m.room.member` event for the creator to join the room. This is\n   needed so the remaining events can be sent.\n\n3. A default `m.room.power_levels` event. Overridden by the\n   `power_level_content_override` parameter.\n\n   In [room versions](https://spec.matrix.org/v1.17/rooms) 1 through 11, the room creator (and not\n   other members) will be given permission to send state events.\n\n   In room versions 12 and later, the room creator is given infinite\n   power level and cannot be specified in the `users` field of\n   `m.room.power_levels`, so is not listed explicitly.\n\n   **Note**: For `trusted_private_chat`, the users specified in the\n   `invite` parameter SHOULD also be appended to `additional_creators`\n   by the server, per the `creation_content` parameter.\n\n   If the room's version is 12 or higher, the power level for sending\n   `m.room.tombstone` events MUST explicitly be higher than `state_default`.\n   For example, set to 150 instead of 100.\n\n4. An `m.room.canonical_alias` event if `room_alias_name` is given.\n\n5. Events set by the `preset`. Currently these are the `m.room.join_rules`,\n   `m.room.history_visibility`, and `m.room.guest_access` state events.\n\n6. Events listed in `initial_state`, in the order that they are\n   listed.\n\n7. Events implied by `name` and `topic` (`m.room.name` and `m.room.topic`\n   state events).\n\n8. Invite events implied by `invite` and `invite_3pid` (`m.room.member` with\n   `membership: invite` and `m.room.third_party_invite`).\n\nThe available presets do the following with respect to room state:\n\n| Preset                 | `join_rules` | `history_visibility` | `guest_access` | Other |\n|------------------------|--------------|----------------------|----------------|-------|\n| `private_chat`         | `invite`     | `shared`             | `can_join`     |       |\n| `trusted_private_chat` | `invite`     | `shared`             | `can_join`     | All invitees are given the same power level as the room creator. |\n| `public_chat`          | `public`     | `shared`             | `forbidden`    |       |\n\nThe server will create a `m.room.create` event in the room with the\nrequesting user as the creator, alongside other keys provided in the\n`creation_content` or implied by behaviour of `creation_content`.",
        "operationId": "createRoom",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "name": {
                    "description": "If this is included, an [`m.room.name`](https://spec.matrix.org/v1.17/client-server-api/#mroomname) event\nwill be sent into the room to indicate the name for the room.\nThis overwrites any [`m.room.name`](https://spec.matrix.org/v1.17/client-server-api/#mroomname)\nevent in `initial_state`.",
                    "type": "string"
                  },
                  "preset": {
                    "description": "Convenience parameter for setting various default state events\nbased on a preset.\n\nIf unspecified, the server should use the `visibility` to determine\nwhich preset to use. A visibility of `public` equates to a preset of\n`public_chat` and `private` visibility equates to a preset of\n`private_chat`.",
                    "enum": [
                      "private_chat",
                      "public_chat",
                      "trusted_private_chat"
                    ],
                    "type": "string"
                  },
                  "topic": {
                    "description": "If this is included, an [`m.room.topic`](https://spec.matrix.org/v1.17/client-server-api/#mroomtopic)\nevent with a `text/plain` mimetype will be sent into the room\nto indicate the topic for the room. This overwrites any\n[`m.room.topic`](https://spec.matrix.org/v1.17/client-server-api/#mroomtopic) event in `initial_state`.",
                    "type": "string"
                  },
                  "visibility": {
                    "description": "The room's visibility in the server's\n[published room directory](https://spec.matrix.org/v1.17/client-server-api#published-room-directory).\nDefaults to `private`.",
                    "enum": [
                      "public",
                      "private"
                    ],
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          },
          "description": "The desired room configuration.",
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "room_id": "!sefiuhWgwghwWgh:example.com"
                    }
                  }
                },
                "schema": {
                  "description": "Information about the newly created room.",
                  "properties": {
                    "room_id": {
                      "description": "The created room's ID.",
                      "type": "string"
                    }
                  },
                  "required": [
                    "room_id"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "Information about the newly created room."
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "\nThe request is invalid. A meaningful `errcode` and description\nerror text will be returned. Example reasons for rejection include:\n\n- The request body is malformed (`errcode` set to `M_BAD_JSON`\n  or `M_NOT_JSON`).\n\n- The room alias specified is already taken (`errcode` set to\n  `M_ROOM_IN_USE`).\n\n- The initial state implied by the parameters to the request is\n  invalid: for example, the user's `power_level` is set below\n  that necessary to set the room name (`errcode` set to\n  `M_INVALID_ROOM_STATE`).\n\n- The homeserver doesn't support the requested room version, or\n  one or more users being invited to the new room are residents\n  of a homeserver which does not support the requested room version.\n  The `errcode` will be `M_UNSUPPORTED_ROOM_VERSION` in these\n  cases."
          }
        },
        "summary": "Create a new room",
        "tags": [
          "Room creation"
        ],
        "x-changedInMatrixVersion": {
          "1.16": "Added server behaviour for how the initial power levels change depending on room version."
        }
      }
    },
    "/_matrix/client/v3/rooms/{room_id}/send/m.room.message/{txnId}": {
      "put": {
        "description": "This endpoint is used to send a message event to a room. Message events\nallow access to historical events and pagination, making them suited\nfor \"once-off\" activity in a room.\n\nThe body of the request should be the content object of the event; the\nfields in this object will vary depending on the type of event. See\n[Room Events](https://spec.matrix.org/v1.17/client-server-api/#room-events) for the m. event specification.",
        "operationId": "sendMessage",
        "x-restler-annotations": [
          {
            "producer_resource_name": "room_id",
            "producer_method": "POST",
            "consumer_param": "room_id",
            "producer_endpoint": "/_matrix/client/v3/createRoom"
          }
        ],
        "parameters": [
          {
            "description": "The created room's ID.",
            "in": "path",
            "name": "room_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The [transaction ID](https://spec.matrix.org/v1.17/client-server-api/#transaction-identifiers) for this event. Clients should generate an\nID unique across requests with the same access token; it will be\nused by the server to ensure idempotency of requests.",
            "in": "path",
            "name": "txnId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "The content of the message event.",
                "properties": {
                  "body": {
                    "description": "The body of the message.",
                    "type": "string"
                  },
                  "msgtype": {
                    "description": "The type of the message. This is used to determine how the\nmessage should be displayed to the user. Clients MUST support\nat least `m.text` messages, and SHOULD support other message types\nas well.",
                    "enum": [
                      "m.text"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "body",
                  "msgtype"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "event_id": "$YUwRidLecu:example.com"
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "event_id": {
                      "description": "A unique identifier for the event.",
                      "type": "string"
                    }
                  },
                  "required": [
                    "event_id"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "An ID for the sent event."
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "The request is invalid. A [standard error response](https://spec.matrix.org/v1.17/client-server-api/#standard-error-response)\nwill be returned. As well as the normal common error codes, other reasons for rejection include:\n\n- `M_DUPLICATE_ANNOTATION`: The request is an attempt to send a [duplicate annotation](https://spec.matrix.org/v1.17/client-server-api/#avoiding-duplicate-annotations)."
          }
        },
        "summary": "Send a message event to the given room.",
        "tags": [
          "Room participation"
        ]
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost:8008"
    }
  ]
}