{
  "components": {
    "securitySchemes": {
      "accessTokenBearer": {
        "description": "The `access_token` obtained during [account registration](https://spec.matrix.org/v1.17/client-server-api/#account-registration)\nor [login](https://spec.matrix.org/v1.17/client-server-api/#login), using the `Authorization: Bearer` header.\n\nIt can also be the `as_token` of an application service.\n\nThis is the preferred method.",
        "scheme": "bearer",
        "type": "http"
      }
    }
  },
  "security": [
    {
      "accessTokenBearer": []
    }
  ],
  "info": {
    "title": "Matrix Client-Server API",
    "version": "v1.17"
  },
  "openapi": "3.1.0",
  "paths": {
    "/_matrix/client/v3/createRoom": {
      "post": {
        "description": "Create a new room with various configuration options.\n\nThe server MUST apply the normal state resolution rules when creating\nthe new room, including checking power levels for each event. It MUST\napply the events implied by the request in the following order:\n\n1. The `m.room.create` event itself. Must be the first event in the\n   room.\n\n2. An `m.room.member` event for the creator to join the room. This is\n   needed so the remaining events can be sent.\n\n3. A default `m.room.power_levels` event. Overridden by the\n   `power_level_content_override` parameter.\n\n   In [room versions](https://spec.matrix.org/v1.17/rooms) 1 through 11, the room creator (and not\n   other members) will be given permission to send state events.\n\n   In room versions 12 and later, the room creator is given infinite\n   power level and cannot be specified in the `users` field of\n   `m.room.power_levels`, so is not listed explicitly.\n\n   **Note**: For `trusted_private_chat`, the users specified in the\n   `invite` parameter SHOULD also be appended to `additional_creators`\n   by the server, per the `creation_content` parameter.\n\n   If the room's version is 12 or higher, the power level for sending\n   `m.room.tombstone` events MUST explicitly be higher than `state_default`.\n   For example, set to 150 instead of 100.\n\n4. An `m.room.canonical_alias` event if `room_alias_name` is given.\n\n5. Events set by the `preset`. Currently these are the `m.room.join_rules`,\n   `m.room.history_visibility`, and `m.room.guest_access` state events.\n\n6. Events listed in `initial_state`, in the order that they are\n   listed.\n\n7. Events implied by `name` and `topic` (`m.room.name` and `m.room.topic`\n   state events).\n\n8. Invite events implied by `invite` and `invite_3pid` (`m.room.member` with\n   `membership: invite` and `m.room.third_party_invite`).\n\nThe available presets do the following with respect to room state:\n\n| Preset                 | `join_rules` | `history_visibility` | `guest_access` | Other |\n|------------------------|--------------|----------------------|----------------|-------|\n| `private_chat`         | `invite`     | `shared`             | `can_join`     |       |\n| `trusted_private_chat` | `invite`     | `shared`             | `can_join`     | All invitees are given the same power level as the room creator. |\n| `public_chat`          | `public`     | `shared`             | `forbidden`    |       |\n\nThe server will create a `m.room.create` event in the room with the\nrequesting user as the creator, alongside other keys provided in the\n`creation_content` or implied by behaviour of `creation_content`.",
        "operationId": "createRoom",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "name": {
                    "description": "If this is included, an [`m.room.name`](https://spec.matrix.org/v1.17/client-server-api/#mroomname) event\nwill be sent into the room to indicate the name for the room.\nThis overwrites any [`m.room.name`](https://spec.matrix.org/v1.17/client-server-api/#mroomname)\nevent in `initial_state`.",
                    "type": "string"
                  },
                  "preset": {
                    "description": "Convenience parameter for setting various default state events\nbased on a preset.\n\nIf unspecified, the server should use the `visibility` to determine\nwhich preset to use. A visibility of `public` equates to a preset of\n`public_chat` and `private` visibility equates to a preset of\n`private_chat`.",
                    "enum": [
                      "private_chat",
                      "public_chat",
                      "trusted_private_chat"
                    ],
                    "type": "string"
                  },
                  "topic": {
                    "description": "If this is included, an [`m.room.topic`](https://spec.matrix.org/v1.17/client-server-api/#mroomtopic)\nevent with a `text/plain` mimetype will be sent into the room\nto indicate the topic for the room. This overwrites any\n[`m.room.topic`](https://spec.matrix.org/v1.17/client-server-api/#mroomtopic) event in `initial_state`.",
                    "type": "string"
                  },
                  "visibility": {
                    "description": "The room's visibility in the server's\n[published room directory](https://spec.matrix.org/v1.17/client-server-api#published-room-directory).\nDefaults to `private`.",
                    "enum": [
                      "public",
                      "private"
                    ],
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          },
          "description": "The desired room configuration.",
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "room_id": "!sefiuhWgwghwWgh:example.com"
                    }
                  }
                },
                "schema": {
                  "description": "Information about the newly created room.",
                  "properties": {
                    "room_id": {
                      "description": "The created room's ID.",
                      "type": "string"
                    }
                  },
                  "required": [
                    "room_id"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "Information about the newly created room."
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "\nThe request is invalid. A meaningful `errcode` and description\nerror text will be returned. Example reasons for rejection include:\n\n- The request body is malformed (`errcode` set to `M_BAD_JSON`\n  or `M_NOT_JSON`).\n\n- The room alias specified is already taken (`errcode` set to\n  `M_ROOM_IN_USE`).\n\n- The initial state implied by the parameters to the request is\n  invalid: for example, the user's `power_level` is set below\n  that necessary to set the room name (`errcode` set to\n  `M_INVALID_ROOM_STATE`).\n\n- The homeserver doesn't support the requested room version, or\n  one or more users being invited to the new room are residents\n  of a homeserver which does not support the requested room version.\n  The `errcode` will be `M_UNSUPPORTED_ROOM_VERSION` in these\n  cases."
          }
        },
        "summary": "Create a new room",
        "tags": [
          "Room creation"
        ],
        "x-changedInMatrixVersion": {
          "1.16": "Added server behaviour for how the initial power levels change depending on room version."
        }
      }
    },
    "/_matrix/client/v3/rooms/{room_id}/send/m.room.message/{txnId}": {
      "put": {
        "description": "This endpoint is used to send a message event to a room. Message events\nallow access to historical events and pagination, making them suited\nfor \"once-off\" activity in a room.\n\nThe body of the request should be the content object of the event; the\nfields in this object will vary depending on the type of event. See\n[Room Events](https://spec.matrix.org/v1.17/client-server-api/#room-events) for the m. event specification.",
        "operationId": "sendMessage",
        "x-restler-annotations": [
          {
            "producer_resource_name": "room_id",
            "producer_method": "POST",
            "consumer_param": "room_id",
            "producer_endpoint": "/_matrix/client/v3/createRoom"
          }
        ],
        "parameters": [
          {
            "description": "The created room's ID.",
            "in": "path",
            "name": "room_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The [transaction ID](https://spec.matrix.org/v1.17/client-server-api/#transaction-identifiers) for this event. Clients should generate an\nID unique across requests with the same access token; it will be\nused by the server to ensure idempotency of requests.",
            "in": "path",
            "name": "txnId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "The content of the message event.",
                "properties": {
                  "body": {
                    "description": "The body of the message.",
                    "type": "string"
                  },
                  "msgtype": {
                    "description": "The type of the message. This is used to determine how the\nmessage should be displayed to the user. Clients MUST support\nat least `m.text` messages, and SHOULD support other message types\nas well.",
                    "enum": [
                      "m.text"
                    ],
                    "type": "string"
                  }
                },
                "required": [
                  "body",
                  "msgtype"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "event_id": "$YUwRidLecu:example.com"
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "event_id": {
                      "description": "A unique identifier for the event.",
                      "type": "string"
                    }
                  },
                  "required": [
                    "event_id"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "An ID for the sent event."
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "The request is invalid. A [standard error response](https://spec.matrix.org/v1.17/client-server-api/#standard-error-response)\nwill be returned. As well as the normal common error codes, other reasons for rejection include:\n\n- `M_DUPLICATE_ANNOTATION`: The request is an attempt to send a [duplicate annotation](https://spec.matrix.org/v1.17/client-server-api/#avoiding-duplicate-annotations)."
          }
        },
        "summary": "Send a message event to the given room.",
        "tags": [
          "Room participation"
        ]
      }
    },
    "/_matrix/client/v3/rooms/{room_id}/leave": {
      "post": {
        "description": "This API stops a user participating in a particular room.\n\nIf the user was already in the room, they will no longer be able to see\nnew events in the room. If the room requires an invite to join, they\nwill need to be re-invited before they can re-join.\n\nIf the user was invited to the room, but had not joined, this call\nserves to reject the invite.\n\nThe user will still be allowed to retrieve history from the room which\nthey were previously allowed to see.",
        "operationId": "leaveRoom",
        "x-restler-annotations": [
          {
            "producer_resource_name": "room_id",
            "producer_method": "POST",
            "consumer_param": "room_id",
            "producer_endpoint": "/_matrix/client/v3/createRoom"
          }
        ],
        "parameters": [
          {
            "description": "The room identifier to leave.",
            "example": "!nkl290a:matrix.org",
            "in": "path",
            "name": "room_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "reason": "Saying farewell - thanks for the support!"
                },
                "properties": {
                  "reason": {
                    "description": "Optional reason to be included as the `reason` on the subsequent\nmembership event.",
                    "type": "string",
                    "x-addedInMatrixVersion": "1.1"
                  }
                },
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {}
                  }
                },
                "schema": {
                  "type": "object"
                }
              }
            },
            "description": "The room has been left."
          },
          "429": {
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "description": "A Matrix-level Error",
                      "properties": {
                        "errcode": {
                          "description": "An error code.",
                          "example": "M_UNKNOWN",
                          "type": "string"
                        },
                        "error": {
                          "description": "A human-readable error message.",
                          "example": "An unknown error occurred",
                          "type": "string"
                        }
                      },
                      "required": [
                        "errcode"
                      ],
                      "title": "Error",
                      "type": "object"
                    },
                    {
                      "description": "The rate limit was reached for this request",
                      "properties": {
                        "errcode": {
                          "description": "The M_LIMIT_EXCEEDED error code",
                          "example": "M_LIMIT_EXCEEDED",
                          "type": "string"
                        },
                        "error": {
                          "description": "A human-readable error message.",
                          "example": "Too many requests",
                          "type": "string"
                        },
                        "retry_after_ms": {
                          "description": "The amount of time in milliseconds the client should wait\nbefore trying the request again.",
                          "example": 2000,
                          "type": "integer"
                        }
                      },
                      "required": [
                        "errcode"
                      ],
                      "title": "RateLimitError",
                      "type": "object"
                    }
                  ]
                }
              }
            },
            "description": "This request was rate-limited."
          }
        },
        "summary": "Stop the requesting user participating in a particular room.",
        "tags": [
          "Room membership"
        ]
      }
    },
    "/_matrix/client/v3/rooms/{room_id}/join": {
      "post": {
        "description": "*Note that this API requires a room ID, not alias.*\n`/join/{room_idOrAlias}` *exists if you have a room alias.*\n\nThis API starts a user's participation in a particular room, if that user\nis allowed to participate in that room. After this call, the client is\nallowed to see all current state events in the room, and all subsequent\nevents associated with the room until the user leaves the room.\n\nAfter a user has joined a room, the room will appear as an entry in the\nresponse of the [`/initialSync`](https://spec.matrix.org/v1.17/client-server-api/#get_matrixclientv3initialsync)\nand [`/sync`](https://spec.matrix.org/v1.17/client-server-api/#get_matrixclientv3sync) APIs.",
        "operationId": "joinRoomById",
        "x-restler-annotations": [
          {
            "producer_resource_name": "room_id",
            "producer_method": "POST",
            "consumer_param": "room_id",
            "producer_endpoint": "/_matrix/client/v3/createRoom"
          }
        ],
        "parameters": [
          {
            "description": "The room identifier (not alias) to join.",
            "example": "!d41d8cd:matrix.org",
            "in": "path",
            "name": "room_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "reason": {
                    "description": "Optional reason to be included as the `reason` on the subsequent\nmembership event.",
                    "example": "Looking for support",
                    "type": "string",
                    "x-addedInMatrixVersion": "1.1"
                  }
                },
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "room_id": "!d41d8cd:matrix.org"
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "room_id": {
                      "description": "The joined room ID.",
                      "type": "string"
                    }
                  },
                  "required": [
                    "room_id"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "The room has been joined.\n\nThe joined room ID must be returned in the `room_id` field."
          },
          "403": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "errcode": "M_FORBIDDEN",
                      "error": "You are not invited to this room."
                    }
                  }
                },
                "schema": {
                  "description": "A Matrix-level Error",
                  "properties": {
                    "errcode": {
                      "description": "An error code.",
                      "example": "M_UNKNOWN",
                      "type": "string"
                    },
                    "error": {
                      "description": "A human-readable error message.",
                      "example": "An unknown error occurred",
                      "type": "string"
                    }
                  },
                  "required": [
                    "errcode"
                  ],
                  "title": "Error",
                  "type": "object"
                }
              }
            },
            "description": "You do not have permission to join the room. A meaningful `errcode`\nand description error text will be returned. Example reasons for rejection are:\n\n- The room is invite-only and the user was not invited.\n- The user has been banned from the room.\n- The room is restricted and the user failed to satisfy any of the conditions."
          },
          "429": {
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "description": "A Matrix-level Error",
                      "properties": {
                        "errcode": {
                          "description": "An error code.",
                          "example": "M_UNKNOWN",
                          "type": "string"
                        },
                        "error": {
                          "description": "A human-readable error message.",
                          "example": "An unknown error occurred",
                          "type": "string"
                        }
                      },
                      "required": [
                        "errcode"
                      ],
                      "title": "Error",
                      "type": "object"
                    },
                    {
                      "description": "The rate limit was reached for this request",
                      "properties": {
                        "errcode": {
                          "description": "The M_LIMIT_EXCEEDED error code",
                          "example": "M_LIMIT_EXCEEDED",
                          "type": "string"
                        },
                        "error": {
                          "description": "A human-readable error message.",
                          "example": "Too many requests",
                          "type": "string"
                        },
                        "retry_after_ms": {
                          "description": "The amount of time in milliseconds the client should wait\nbefore trying the request again.",
                          "example": 2000,
                          "type": "integer"
                        }
                      },
                      "required": [
                        "errcode"
                      ],
                      "title": "RateLimitError",
                      "type": "object"
                    }
                  ]
                }
              }
            },
            "description": "This request was rate-limited."
          }
        },
        "summary": "Join the requesting user to a particular room.",
        "tags": [
          "Room membership"
        ]
      }
    },
    "/_matrix/client/v3/rooms/{room_id}/redact/{event_id}/{txnId}": {
      "put": {
        "description": "Strips all information out of an event which isn't critical to the\nintegrity of the server-side representation of the room.\n\nThis cannot be undone.\n\nAny user with a power level greater than or equal to the `m.room.redaction`\nevent power level may send redactions for their own events in the room. If\nthe user's power level is also greater than or equal to the `redact` power\nlevel of the room, the user may redact events sent by other users.\n\nServer administrators may redact events sent by users on their server.",
        "operationId": "redactEvent",
        "x-restler-annotations": [
          {
            "producer_resource_name": "room_id",
            "producer_method": "POST",
            "consumer_param": "room_id",
            "producer_endpoint": "/_matrix/client/v3/createRoom"
          },
          {
            "producer_resource_name": "event_id",
            "producer_method": "PUT",
            "consumer_param": "event_id",
            "producer_endpoint": "/_matrix/client/v3/rooms/{room_id}/send/m.room.message/{txnId}"
          }
        ],
        "parameters": [
          {
            "description": "The room from which to redact the event.",
            "example": "!637q39766251:example.com",
            "in": "path",
            "name": "room_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The ID of the event to redact",
            "example": "bai2b1i9:matrix.org",
            "in": "path",
            "name": "event_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "description": "The [transaction ID](https://spec.matrix.org/v1.17/client-server-api/#transaction-identifiers) for this event. Clients should generate a\nunique ID; it will be used by the server to ensure idempotency of requests.",
            "example": "37",
            "in": "path",
            "name": "txnId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "example": {
                  "reason": "Indecent material"
                },
                "properties": {
                  "reason": {
                    "description": "The reason for the event being redacted.",
                    "type": "string"
                  }
                },
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "event_id": "$YUwQidLecu:example.com"
                    }
                  }
                },
                "schema": {
                  "properties": {
                    "event_id": {
                      "description": "A unique identifier for the event.",
                      "type": "string"
                    }
                  },
                  "type": "object"
                }
              }
            },
            "description": "An ID for the redaction event."
          }
        },
        "summary": "Strips all non-integrity-critical information out of an event.",
        "tags": [
          "Room participation"
        ]
      }
    }
  },
  "servers": [
    {
      "url": "http://localhost:8008"
    }
  ]
}